name: CI-CD

on:
  push:
    branches:
      - main

jobs:
  CI-CD:
    runs-on: ubuntu-latest

    steps:
    # -------------------------
    # Checkout Code
    # -------------------------
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # -------------------------
    # Setup Python
    # -------------------------
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.7"
        cache: "pip"

    # -------------------------
    # Install Dependencies
    # -------------------------
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        pip install dvc

    # -------------------------
    # Configure AWS Credentials
    # -------------------------
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    # -------------------------
    # Pull Data from DVC
    # -------------------------
    - name: DVC Pull
      run: |
        dvc pull

    # -------------------------
    # Run Tests
    # -------------------------
    - name: Test Model Registry
      env:
        DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
      run: |
        pytest tests/test_model_registry.py

    - name: Test Model Performance
      env:
        DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
      run: |
        pytest tests/test_model_performance.py

    # -------------------------
    # Promote Model
    # -------------------------
    - name: Promote Model
      if: success()
      env:
        DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
      run: |
        python promote_model.py

    # -------------------------
    # Login to Amazon ECR
    # -------------------------
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # -------------------------
    # Build and Push Docker Image
    # -------------------------
    - name: Build and Push Docker Image
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: latest
      run: |
        docker build -t $REGISTRY/${{ secrets.AWS_REPOSITORY_NAME }}:$IMAGE_TAG .
        docker push $REGISTRY/${{ secrets.AWS_REPOSITORY_NAME }}:$IMAGE_TAG

    # -------------------------
    # Zip Deployment Files
    # -------------------------
    - name: Zip files for deployment
      if: success()
      run: |
        zip -r deployment.zip appspec.yml deploy/scripts/install_dependencies.sh deploy/scripts/start_docker.sh

    # -------------------------
    # Upload ZIP to S3
    # -------------------------
    - name: Upload ZIP to S3
      if: success()
      run: |
        aws s3 cp deployment.zip s3://demandpredictiondeployment/deployment.zip

    # -------------------------
    # Deploy to AWS CodeDeploy
    # -------------------------
    - name: Deploy to AWS CodeDeploy
      if: success()
      run: |
        aws deploy create-deployment \
          --application-name uber-demand-prediction \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --deployment-group-name uber-demand-prediction-deployment-group \
          --s3-location bucket=demandpredictiondeployment,key=deployment.zip,bundleType=zip \
          --file-exists-behavior OVERWRITE \
          --region eu-north-1